// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc8FVklDnGwAqFXN9fmucRHb5VqMfkaP4',
    appId: '1:429602903859:web:797c589c05f673b9f81046',
    messagingSenderId: '429602903859',
    projectId: 'laour-etf-app',
    authDomain: 'laour-etf-app.firebaseapp.com',
    storageBucket: 'laour-etf-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC07mT1N8fvCEOoKYKm-owMBEwJR_pwfLE',
    appId: '1:429602903859:android:50633d9c181bd2f0f81046',
    messagingSenderId: '429602903859',
    projectId: 'laour-etf-app',
    storageBucket: 'laour-etf-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPd4sUHwljIlwTN9E5F94SZS-AuOs8f8o',
    appId: '1:429602903859:ios:a67836f225640610f81046',
    messagingSenderId: '429602903859',
    projectId: 'laour-etf-app',
    storageBucket: 'laour-etf-app.firebasestorage.app',
    iosBundleId: 'com.example.laourEtf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPd4sUHwljIlwTN9E5F94SZS-AuOs8f8o',
    appId: '1:429602903859:ios:a67836f225640610f81046',
    messagingSenderId: '429602903859',
    projectId: 'laour-etf-app',
    storageBucket: 'laour-etf-app.firebasestorage.app',
    iosBundleId: 'com.example.laourEtf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc8FVklDnGwAqFXN9fmucRHb5VqMfkaP4',
    appId: '1:429602903859:web:348c0e5c83979e0bf81046',
    messagingSenderId: '429602903859',
    projectId: 'laour-etf-app',
    authDomain: 'laour-etf-app.firebaseapp.com',
    storageBucket: 'laour-etf-app.firebasestorage.app',
  );
}